version: 2

jobs:
  test:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run:
          name: angular-build
          command: yarn ng -- build --prod --aot --no-progress
      - run:
          name: angular-test
          command: yarn test -- --no-progress
      - run:
          name: angular-lint
          command: yarn lint

  deploy:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - add_ssh_keys:
          fingerprints:
            - "23:4d:1c:bf:a6:a2:94:56:be:b5:6f:70:34:9b:b9:ad"
      - checkout
      - run:
          name: install-dependencies
          command: yarn install
      - run:
          name: angular-build
          command: yarn ng -- build --prod --extract-css=false --aot --no-progress
      - run:
          name: deploy-to-server
          command: scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./dist/ampnet-frontend root@ampnet.io:/var/www/

workflows:
  version: 2
  test:
    jobs: 
      - test:
          filters:
            branches:
              ignore: master
  deploy:
    jobs:
      - test 
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master


