version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run: npm install
      - run:
          name: Print the Current Time
          command: date