version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run: 
          name: Install AngularCLI
          command: npm install @angular/cli
      - run:
          name: Install Node dependencies
          command: npm install
      - run:
          name: Run tests
          command: ng test
      - run:
          name: Run linter
          command: ng lint