import { NgModule, NO_ERRORS_SCHEMA } from '@angular/core';
import { NativeScriptModule } from 'nativescript-angular/nativescript.module';

import { AppRoutingModule } from './app-routing.module.tns';
import { AppComponent } from './app.component';
import { AutoGeneratedComponent } from './auto-generated/auto-generated.component';
import { MainAdminComponent } from './main-admin/main-admin.component';
import { OnboardingComponent } from './authentication/onboarding/onboarding.component';
import { ManageUsersComponent } from './organizations/manage-users/manage-users.component';
import { DetailsComponent } from './organizations/manage-users/details/details.component';
import { ManageProjectsComponent } from './manage-projects/manage-projects.component';
import { ManageSingleProjectComponent } from './manage-projects/manage-single-project/manage-single-project.component';


// Uncomment and add to NgModule imports if you need to use two-way binding
// import { NativeScriptFormsModule } from 'nativescript-angular/forms';

// Uncomment and add to NgModule imports  if you need to use the HTTP wrapper
// import { NativeScriptHttpClientModule } from 'nativescript-angular/http-client';

@NgModule({
  declarations: [
    AppComponent,
    AutoGeneratedComponent,
    MainAdminComponent,
    OnboardingComponent,
    ManageUsersComponent,
    DetailsComponent,
    ManageProjectsComponent,
    ManageSingleProjectComponent,
  ],
  imports: [
    NativeScriptModule,
    AppRoutingModule,
  ],
  providers: [],
  bootstrap: [AppComponent],
  schemas: [NO_ERRORS_SCHEMA]
})
/*
Pass your application module to the bootstrapModule function located in main.ts to start your app
*/
export class AppModule { }
